<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mab_picture_references"
 *
 * Auto generated by Extension Builder 2015-11-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Opening times',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marcel Briefs',
	'author_email' => 't3@lbrmedia.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);